apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - cluster-secret-cleanup.yaml
  - delete-aro.yaml
  - delete-ocp-aws.yaml
  - delete-osd.yaml
  - delete-rosa.yaml
  - get-cluster-id.yaml
  - get-osd-credentials.yaml
  - ocm-login.yaml
  - operator-pod-restart.yaml
  - parameter-sanity-check.yaml
  - pause-pipeline.yaml
  - prepare-for-rhcl-rc-install.yaml
  - provision-aro.yaml
  - provision-ocp-aws.yaml
  - provision-osd-aws.yaml
  - provision-osd-gcp.yaml
  - provision-rosa.yaml
  - rosa-login.yaml
  - upgrade-to-latest.yaml
  - wait-for-valid-certificates.yaml
  - wait-till-osd-is-deleted.yaml
  - wait-till-osd-is-ready.yaml
  - helm-uninstall.yaml
  - do-custom-updates.yaml
